/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrackingEntry {
    status: ShipmentStatus;
    notes?: string;
    timestamp: bigint;
    location: string;
}
export interface ShipmentDetails {
    weight: number;
    destination: Address;
    itemDescription: string;
    pickup: Address;
    dimensions: string;
}
export interface CustomerInfo {
    name: string;
    company?: string;
    contactDetails: string;
}
export interface Booking {
    serviceType: ServiceType;
    customer: CustomerInfo;
    estimatedDelivery: bigint;
    shipment: ShipmentDetails;
    pickupTime: bigint;
    trackingHistory: Array<TrackingEntry>;
    shipmentId: string;
    currentStatus: ShipmentStatus;
}
export interface Address {
    zip: string;
    street: string;
    country: string;
    city: string;
    state: string;
}
export enum ServiceType {
    expedited = "expedited",
    dedicatedFreight = "dedicatedFreight",
    longHaul = "longHaul",
    regional = "regional"
}
export enum ShipmentStatus {
    outForDelivery = "outForDelivery",
    inTransit = "inTransit",
    pickedUp = "pickedUp",
    delivered = "delivered"
}
export interface backendInterface {
    createBooking(customer: CustomerInfo, shipment: ShipmentDetails, serviceType: ServiceType, pickupTime: bigint): Promise<string>;
    estimateQuote(pickup: Address, destination: Address, weight: number, itemType: string, serviceType: ServiceType): Promise<number>;
    getAllBookingsByPickupTime(): Promise<Array<Booking>>;
    getBooking(shipmentId: string): Promise<Booking>;
    getBookingsByStatus(status: ShipmentStatus): Promise<Array<Booking>>;
    trackShipment(shipmentId: string): Promise<{
        estimatedDelivery: bigint;
        trackingHistory: Array<TrackingEntry>;
        currentStatus: ShipmentStatus;
    }>;
    updateTracking(shipmentId: string, location: string, status: ShipmentStatus, notes: string | null): Promise<void>;
}
import type { Booking as _Booking, CustomerInfo as _CustomerInfo, ServiceType as _ServiceType, ShipmentDetails as _ShipmentDetails, ShipmentStatus as _ShipmentStatus, TrackingEntry as _TrackingEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBooking(arg0: CustomerInfo, arg1: ShipmentDetails, arg2: ServiceType, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_CustomerInfo_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_ServiceType_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_CustomerInfo_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_ServiceType_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async estimateQuote(arg0: Address, arg1: Address, arg2: number, arg3: string, arg4: ServiceType): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateQuote(arg0, arg1, arg2, arg3, to_candid_ServiceType_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateQuote(arg0, arg1, arg2, arg3, to_candid_ServiceType_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async getAllBookingsByPickupTime(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingsByPickupTime();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingsByPickupTime();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByStatus(arg0: ShipmentStatus): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByStatus(to_candid_ShipmentStatus_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByStatus(to_candid_ShipmentStatus_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async trackShipment(arg0: string): Promise<{
        estimatedDelivery: bigint;
        trackingHistory: Array<TrackingEntry>;
        currentStatus: ShipmentStatus;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.trackShipment(arg0);
                return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackShipment(arg0);
            return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTracking(arg0: string, arg1: string, arg2: ShipmentStatus, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTracking(arg0, arg1, to_candid_ShipmentStatus_n18(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTracking(arg0, arg1, to_candid_ShipmentStatus_n18(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_Booking_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerInfo_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerInfo): CustomerInfo {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ShipmentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShipmentStatus): ShipmentStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TrackingEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackingEntry): TrackingEntry {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    company: [] | [string];
    contactDetails: string;
}): {
    name: string;
    company?: string;
    contactDetails: string;
} {
    return {
        name: value.name,
        company: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.company)),
        contactDetails: value.contactDetails
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ShipmentStatus;
    notes: [] | [string];
    timestamp: bigint;
    location: string;
}): {
    status: ShipmentStatus;
    notes?: string;
    timestamp: bigint;
    location: string;
} {
    return {
        status: from_candid_ShipmentStatus_n16(_uploadFile, _downloadFile, value.status),
        notes: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        location: value.location
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    estimatedDelivery: bigint;
    trackingHistory: Array<_TrackingEntry>;
    currentStatus: _ShipmentStatus;
}): {
    estimatedDelivery: bigint;
    trackingHistory: Array<TrackingEntry>;
    currentStatus: ShipmentStatus;
} {
    return {
        estimatedDelivery: value.estimatedDelivery,
        trackingHistory: from_candid_vec_n13(_uploadFile, _downloadFile, value.trackingHistory),
        currentStatus: from_candid_ShipmentStatus_n16(_uploadFile, _downloadFile, value.currentStatus)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: _ServiceType;
    customer: _CustomerInfo;
    estimatedDelivery: bigint;
    shipment: _ShipmentDetails;
    pickupTime: bigint;
    trackingHistory: Array<_TrackingEntry>;
    shipmentId: string;
    currentStatus: _ShipmentStatus;
}): {
    serviceType: ServiceType;
    customer: CustomerInfo;
    estimatedDelivery: bigint;
    shipment: ShipmentDetails;
    pickupTime: bigint;
    trackingHistory: Array<TrackingEntry>;
    shipmentId: string;
    currentStatus: ShipmentStatus;
} {
    return {
        serviceType: from_candid_ServiceType_n8(_uploadFile, _downloadFile, value.serviceType),
        customer: from_candid_CustomerInfo_n10(_uploadFile, _downloadFile, value.customer),
        estimatedDelivery: value.estimatedDelivery,
        shipment: value.shipment,
        pickupTime: value.pickupTime,
        trackingHistory: from_candid_vec_n13(_uploadFile, _downloadFile, value.trackingHistory),
        shipmentId: value.shipmentId,
        currentStatus: from_candid_ShipmentStatus_n16(_uploadFile, _downloadFile, value.currentStatus)
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outForDelivery: null;
} | {
    inTransit: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
}): ShipmentStatus {
    return "outForDelivery" in value ? ShipmentStatus.outForDelivery : "inTransit" in value ? ShipmentStatus.inTransit : "pickedUp" in value ? ShipmentStatus.pickedUp : "delivered" in value ? ShipmentStatus.delivered : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expedited: null;
} | {
    dedicatedFreight: null;
} | {
    longHaul: null;
} | {
    regional: null;
}): ServiceType {
    return "expedited" in value ? ServiceType.expedited : "dedicatedFreight" in value ? ServiceType.dedicatedFreight : "longHaul" in value ? ServiceType.longHaul : "regional" in value ? ServiceType.regional : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrackingEntry>): Array<TrackingEntry> {
    return value.map((x)=>from_candid_TrackingEntry_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CustomerInfo_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerInfo): _CustomerInfo {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ShipmentStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentStatus): _ShipmentStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    company?: string;
    contactDetails: string;
}): {
    name: string;
    company: [] | [string];
    contactDetails: string;
} {
    return {
        name: value.name,
        company: value.company ? candid_some(value.company) : candid_none(),
        contactDetails: value.contactDetails
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentStatus): {
    outForDelivery: null;
} | {
    inTransit: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} {
    return value == ShipmentStatus.outForDelivery ? {
        outForDelivery: null
    } : value == ShipmentStatus.inTransit ? {
        inTransit: null
    } : value == ShipmentStatus.pickedUp ? {
        pickedUp: null
    } : value == ShipmentStatus.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    expedited: null;
} | {
    dedicatedFreight: null;
} | {
    longHaul: null;
} | {
    regional: null;
} {
    return value == ServiceType.expedited ? {
        expedited: null
    } : value == ServiceType.dedicatedFreight ? {
        dedicatedFreight: null
    } : value == ServiceType.longHaul ? {
        longHaul: null
    } : value == ServiceType.regional ? {
        regional: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
