/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerInfo = IDL.Record({
  'name' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'contactDetails' : IDL.Text,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const ShipmentDetails = IDL.Record({
  'weight' : IDL.Float64,
  'destination' : Address,
  'itemDescription' : IDL.Text,
  'pickup' : Address,
  'dimensions' : IDL.Text,
});
export const ServiceType = IDL.Variant({
  'expedited' : IDL.Null,
  'dedicatedFreight' : IDL.Null,
  'longHaul' : IDL.Null,
  'regional' : IDL.Null,
});
export const ShipmentStatus = IDL.Variant({
  'outForDelivery' : IDL.Null,
  'inTransit' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
});
export const TrackingEntry = IDL.Record({
  'status' : ShipmentStatus,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
});
export const Booking = IDL.Record({
  'serviceType' : ServiceType,
  'customer' : CustomerInfo,
  'estimatedDelivery' : IDL.Int,
  'shipment' : ShipmentDetails,
  'pickupTime' : IDL.Int,
  'trackingHistory' : IDL.Vec(TrackingEntry),
  'shipmentId' : IDL.Text,
  'currentStatus' : ShipmentStatus,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func(
      [CustomerInfo, ShipmentDetails, ServiceType, IDL.Int],
      [IDL.Text],
      [],
    ),
  'estimateQuote' : IDL.Func(
      [Address, Address, IDL.Float64, IDL.Text, ServiceType],
      [IDL.Float64],
      [],
    ),
  'getAllBookingsByPickupTime' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
  'getBookingsByStatus' : IDL.Func(
      [ShipmentStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'trackShipment' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'estimatedDelivery' : IDL.Int,
          'trackingHistory' : IDL.Vec(TrackingEntry),
          'currentStatus' : ShipmentStatus,
        }),
      ],
      ['query'],
    ),
  'updateTracking' : IDL.Func(
      [IDL.Text, IDL.Text, ShipmentStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerInfo = IDL.Record({
    'name' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'contactDetails' : IDL.Text,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const ShipmentDetails = IDL.Record({
    'weight' : IDL.Float64,
    'destination' : Address,
    'itemDescription' : IDL.Text,
    'pickup' : Address,
    'dimensions' : IDL.Text,
  });
  const ServiceType = IDL.Variant({
    'expedited' : IDL.Null,
    'dedicatedFreight' : IDL.Null,
    'longHaul' : IDL.Null,
    'regional' : IDL.Null,
  });
  const ShipmentStatus = IDL.Variant({
    'outForDelivery' : IDL.Null,
    'inTransit' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const TrackingEntry = IDL.Record({
    'status' : ShipmentStatus,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
  });
  const Booking = IDL.Record({
    'serviceType' : ServiceType,
    'customer' : CustomerInfo,
    'estimatedDelivery' : IDL.Int,
    'shipment' : ShipmentDetails,
    'pickupTime' : IDL.Int,
    'trackingHistory' : IDL.Vec(TrackingEntry),
    'shipmentId' : IDL.Text,
    'currentStatus' : ShipmentStatus,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func(
        [CustomerInfo, ShipmentDetails, ServiceType, IDL.Int],
        [IDL.Text],
        [],
      ),
    'estimateQuote' : IDL.Func(
        [Address, Address, IDL.Float64, IDL.Text, ServiceType],
        [IDL.Float64],
        [],
      ),
    'getAllBookingsByPickupTime' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
    'getBookingsByStatus' : IDL.Func(
        [ShipmentStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'trackShipment' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'estimatedDelivery' : IDL.Int,
            'trackingHistory' : IDL.Vec(TrackingEntry),
            'currentStatus' : ShipmentStatus,
          }),
        ],
        ['query'],
      ),
    'updateTracking' : IDL.Func(
        [IDL.Text, IDL.Text, ShipmentStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };