/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface Booking {
  'serviceType' : ServiceType,
  'customer' : CustomerInfo,
  'estimatedDelivery' : bigint,
  'shipment' : ShipmentDetails,
  'pickupTime' : bigint,
  'trackingHistory' : Array<TrackingEntry>,
  'shipmentId' : string,
  'currentStatus' : ShipmentStatus,
}
export interface CustomerInfo {
  'name' : string,
  'company' : [] | [string],
  'contactDetails' : string,
}
export type ServiceType = { 'expedited' : null } |
  { 'dedicatedFreight' : null } |
  { 'longHaul' : null } |
  { 'regional' : null };
export interface ShipmentDetails {
  'weight' : number,
  'destination' : Address,
  'itemDescription' : string,
  'pickup' : Address,
  'dimensions' : string,
}
export type ShipmentStatus = { 'outForDelivery' : null } |
  { 'inTransit' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null };
export interface TrackingEntry {
  'status' : ShipmentStatus,
  'notes' : [] | [string],
  'timestamp' : bigint,
  'location' : string,
}
export interface _SERVICE {
  'createBooking' : ActorMethod<
    [CustomerInfo, ShipmentDetails, ServiceType, bigint],
    string
  >,
  'estimateQuote' : ActorMethod<
    [Address, Address, number, string, ServiceType],
    number
  >,
  'getAllBookingsByPickupTime' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[string], Booking>,
  'getBookingsByStatus' : ActorMethod<[ShipmentStatus], Array<Booking>>,
  'trackShipment' : ActorMethod<
    [string],
    {
      'estimatedDelivery' : bigint,
      'trackingHistory' : Array<TrackingEntry>,
      'currentStatus' : ShipmentStatus,
    }
  >,
  'updateTracking' : ActorMethod<
    [string, string, ShipmentStatus, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];